#!/bin/bash

interface=$6
if [ -z "$interface" ]; then
    exit
fi

if ! /usr/bin/systemctl -q is-active vyos-hostsd; then
    exit  # vyos-hostsd is not running
fi

hostsd_client="/usr/bin/vyos-hostsd-client"

$hostsd_client --delete-name-servers --tag "dhcp-$interface"

if [ "$USEPEERDNS" ] && [ -n "$DNS1" ]; then
$hostsd_client --add-name-servers "$DNS1" --tag "dhcp-$interface"
fi
if [ "$USEPEERDNS" ] && [ -n "$DNS2" ]; then
$hostsd_client --add-name-servers "$DNS2" --tag "dhcp-$interface"
fi

$hostsd_client --apply
