#!/usr/bin/env python3
#
# Copyright (C) 2024 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# - Move 'require' from 'protocols' in  'authentication' node
# - Migrate to new default values in radius timeout and acct-timeout

from sys import argv
from sys import exit
from vyos.configtree import ConfigTree

if len(argv) < 2:
    print("Must specify file name!")
    exit(1)

file_name = argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

config = ConfigTree(config_file)
base = ['vpn', 'pptp', 'remote-access']

if not config.exists(base):
    exit(0)

#migrate require to protocols
require_path = base + ['authentication', 'require']
if config.exists(require_path):
    protocols = list(config.return_values(require_path))
    for protocol in protocols:
        config.set(base + ['authentication', 'protocols'], value=protocol,
                   replace=False)
    config.delete(require_path)
else:
    config.set(base + ['authentication', 'protocols'], value='mschap-v2')

radius_path = base + ['authentication', 'radius']
if config.exists(radius_path):
    if not config.exists(radius_path + ['timeout']):
        config.set(radius_path + ['timeout'], value=3)
    if not config.exists(radius_path + ['acct-timeout']):
        config.set(radius_path + ['acct-timeout'], value=3)


try:
    with open(file_name, 'w') as f:
        f.write(config.to_string())
except OSError as e:
    print("Failed to save the modified config: {}".format(e))
    exit(1)
