#!/usr/bin/env python3
#
# Copyright (C) 2024 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# T6011: rpki: known-hosts-file is no longer supported bxy FRR CLI,
#        remove VyOS CLI node

from sys import exit
from sys import argv
from vyos.configtree import ConfigTree

if len(argv) < 2:
    print("Must specify file name!")
    exit(1)

file_name = argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

base = ['protocols', 'rpki']
config = ConfigTree(config_file)

# Nothing to do
if not config.exists(base):
    exit(0)

if config.exists(base + ['cache']):
    for cache in config.list_nodes(base + ['cache']):
        ssh_node = base + ['cache', cache, 'ssh']
        if config.exists(ssh_node + ['known-hosts-file']):
            config.delete(ssh_node + ['known-hosts-file'])

try:
    with open(file_name, 'w') as f:
        f.write(config.to_string())
except OSError as e:
    print("Failed to save the modified config: {}".format(e))
    exit(1)
