#!/usr/bin/env python3
#
# Copyright (C) 2020 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Delete log_file, log_level and user nodes
# rename hash_type to hash
# rename mine_interval to interval

from sys import argv,exit

from vyos.configtree import ConfigTree

if len(argv) < 2:
    print("Must specify file name!")
    exit(1)

file_name = argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

config = ConfigTree(config_file)

base = ['service', 'salt-minion']
if not config.exists(base):
    # Nothing to do
    exit(0)
else:

    # delete nodes which are now populated with sane defaults
    for node in ['log_file', 'log_level', 'user']:
        if config.exists(base + [node]):
            config.delete(base + [node])

    if config.exists(base + ['hash_type']):
        config.rename(base + ['hash_type'], 'hash')

    if config.exists(base + ['mine_interval']):
        config.rename(base + ['mine_interval'], 'interval')

    try:
        with open(file_name, 'w') as f:
            f.write(config.to_string())
    except OSError as e:
        print("Failed to save the modified config: {}".format(e))
        exit(1)
