#!/usr/bin/env python3
#
# Copyright (C) 2022 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# re-organize route-map as-path

from sys import argv
from sys import exit

from vyos.configtree import ConfigTree

if len(argv) < 2:
    print("Must specify file name!")
    exit(1)

file_name = argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

base = ['policy', 'route-map']

config = ConfigTree(config_file)
if not config.exists(base):
    # Nothing to do
    exit(0)

for route_map in config.list_nodes(base):
    # Bail out Early
    if not config.exists(base + [route_map, 'rule']):
        continue

    for rule in config.list_nodes(base + [route_map, 'rule']):
        rule_base = base + [route_map, 'rule', rule]
        if config.exists(rule_base + ['set', 'as-path-exclude']):
            tmp = config.return_value(rule_base + ['set', 'as-path-exclude'])
            config.delete(rule_base + ['set', 'as-path-exclude'])
            config.set(rule_base + ['set', 'as-path', 'exclude'], value=tmp)

        if config.exists(rule_base + ['set', 'as-path-prepend']):
            tmp = config.return_value(rule_base + ['set', 'as-path-prepend'])
            config.delete(rule_base + ['set', 'as-path-prepend'])
            config.set(rule_base + ['set', 'as-path', 'prepend'], value=tmp)

try:
    with open(file_name, 'w') as f:
        f.write(config.to_string())
except OSError as e:
    print("Failed to save the modified config: {}".format(e))
    exit(1)
