#!/usr/bin/env python3
#
# Copyright (C) 2020 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# T3043: rename Wireless interface security mode 'both' to 'wpa+wpa2'
# T3043: move "system wifi-regulatory-domain" to indicidual wireless interface

from sys import exit, argv
from vyos.configtree import ConfigTree

if __name__ == '__main__':
    if len(argv) < 2:
        print("Must specify file name!")
        exit(1)

    file_name = argv[1]
    with open(file_name, 'r') as f:
        config_file = f.read()

    config = ConfigTree(config_file)
    base = ['interfaces', 'wireless']
    if not config.exists(base):
        # Nothing to do
        exit(0)

    country_code = ''
    cc_cli = ['system', 'wifi-regulatory-domain']
    if config.exists(cc_cli):
        country_code = config.return_value(cc_cli)
        config.delete(cc_cli)

    for wifi in config.list_nodes(base):
        sec_mode = base + [wifi, 'security', 'wpa', 'mode']
        if config.exists(sec_mode):
            mode = config.return_value(sec_mode)
            if mode == 'both':
                config.set(sec_mode, value='wpa+wpa2', replace=True)

        if country_code:
            config.set(base + [wifi, 'country-code'], value=country_code)

    try:
        with open(file_name, 'w') as f:
            f.write(config.to_string())
    except OSError as e:
        print("Failed to save the modified config: {}".format(e))
        exit(1)
