#!/usr/bin/env python3
#
# Copyright (C) 2020 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# T3048: remove smp-affinity node from ethernet and use tuned instead

from sys import exit, argv
from vyos.configtree import ConfigTree

if __name__ == '__main__':
    if len(argv) < 2:
        print("Must specify file name!")
        exit(1)

    file_name = argv[1]
    with open(file_name, 'r') as f:
        config_file = f.read()

    config = ConfigTree(config_file)
    base = ['interfaces', 'ethernet']

    if not config.exists(base):
        # Nothing to do
        exit(0)

    migrate = False
    for interface in config.list_nodes(base):
        smp_base = base + [interface, 'smp-affinity']
        # if any one interface had smp-affinity configured manually, we will
        # configure "system option performance"
        if config.exists(smp_base):
            if config.return_value(smp_base) != 'auto':
                migrate = True
            config.delete(smp_base)

    if migrate:
        config.set(['system', 'options', 'performance'], value='throughput')

    try:
        with open(file_name, 'w') as f:
            f.write(config.to_string())
    except OSError as e:
        print("Failed to save the modified config: {}".format(e))
        exit(1)
