#!/usr/bin/env python3
#
# Copyright (C) 2020 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Command line migration of port mirroring
# https://vyos.dev/T3089

import sys
from vyos.configtree import ConfigTree

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Must specify file name!")
        sys.exit(1)

    file_name = sys.argv[1]

    with open(file_name, 'r') as f:
        config_file = f.read()

    config = ConfigTree(config_file)
    base = ['interfaces', 'ethernet']
    if not config.exists(base):
        # Nothing to do
        sys.exit(0)

    for interface in config.list_nodes(base):
        mirror_old_base = base + [interface, 'mirror']
        if config.exists(mirror_old_base):
            intf = config.return_values(mirror_old_base)
            if config.exists(mirror_old_base):
                config.delete(mirror_old_base)
                config.set(mirror_old_base + ['ingress'],intf[0])

    try:
        with open(file_name, 'w') as f:
            f.write(config.to_string())
    except OSError as e:
        print("Failed to save the modified config: {}".format(e))
        sys.exit(1)
