#!/usr/bin/env python3
#
# Copyright (C) 2021 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from sys import argv
from sys import exit
from vyos.configtree import ConfigTree

def migrate_ospf(config, path, interface):
    path = path + ['ospf']
    if config.exists(path):
        new_base = ['protocols', 'ospf', 'interface']
        config.set(new_base)
        config.set_tag(new_base)
        config.copy(path, new_base + [interface])
        config.delete(path)

        # if "ip ospf" was the only setting, we can clean out the empty
        # ip node afterwards
        if len(config.list_nodes(path[:-1])) == 0:
            config.delete(path[:-1])

def migrate_rip(config, path, interface):
    path = path + ['rip']
    if config.exists(path):
        new_base = ['protocols', 'rip', 'interface']
        config.set(new_base)
        config.set_tag(new_base)
        config.copy(path, new_base + [interface])
        config.delete(path)

        # if "ip rip" was the only setting, we can clean out the empty
        # ip node afterwards
        if len(config.list_nodes(path[:-1])) == 0:
            config.delete(path[:-1])

if __name__ == '__main__':
    if (len(argv) < 1):
        print("Must specify file name!")
        exit(1)

    file_name = argv[1]
    with open(file_name, 'r') as f:
        config_file = f.read()

    config = ConfigTree(config_file)

    #
    # Migrate "interface ethernet eth0 ip ospf" to "protocols ospf interface eth0"
    #
    for type in config.list_nodes(['interfaces']):
        for interface in config.list_nodes(['interfaces', type]):
            if_base = ['interfaces', type, interface, 'ip']
            migrate_rip(config, if_base, interface)
            migrate_ospf(config, if_base, interface)

            vif_path = ['interfaces', type, interface, 'vif']
            if config.exists(vif_path):
                for vif in config.list_nodes(vif_path):
                    vif_if_base = vif_path + [vif, 'ip']
                    migrate_rip(config, vif_if_base, f'{interface}.{vif}')
                    migrate_ospf(config, vif_if_base, f'{interface}.{vif}')

            vif_s_path = ['interfaces', type, interface, 'vif-s']
            if config.exists(vif_s_path):
                for vif_s in config.list_nodes(vif_s_path):
                    vif_s_if_base = vif_s_path + [vif_s, 'ip']

                    # vif-c interfaces MUST be migrated before their parent vif-s
                    # interface as the migrate_*() functions delete the path!
                    vif_c_path = ['interfaces', type, interface, 'vif-s', vif_s, 'vif-c']
                    if config.exists(vif_c_path):
                        for vif_c in config.list_nodes(vif_c_path):
                            vif_c_if_base = vif_c_path + [vif_c, 'ip']
                            migrate_rip(config, vif_c_if_base, f'{interface}.{vif_s}.{vif_c}')
                            migrate_ospf(config, vif_c_if_base, f'{interface}.{vif_s}.{vif_c}')

                    migrate_rip(config, vif_s_if_base, f'{interface}.{vif_s}')
                    migrate_ospf(config, vif_s_if_base, f'{interface}.{vif_s}')

    try:
        with open(file_name, 'w') as f:
            f.write(config.to_string())
    except OSError as e:
        print("Failed to save the modified config: {}".format(e))
        exit(1)
