#!/usr/bin/env python3
#
# Copyright (C) 2021 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# A VTI interface also requires an IPSec configuration - VyOS 1.2 supported
# having a VTI interface in the CLI but no IPSec configuration - drop VTI
# configuration if this is the case for VyOS 1.4

import os
import sys
from vyos.configtree import ConfigTree

if __name__ == '__main__':
    if (len(sys.argv) < 1):
        print("Must specify file name!")
        sys.exit(1)

    file_name = sys.argv[1]

    with open(file_name, 'r') as f:
        config_file = f.read()

    config = ConfigTree(config_file)
    base = ['interfaces', 'wireguard']
    if not config.exists(base):
        # Nothing to do
        sys.exit(0)

    for interface in config.list_nodes(base):
        private_key_path = base + [interface, 'private-key']
        
        key_file = 'default'
        if config.exists(private_key_path):
            key_file = config.return_value(private_key_path)

        full_key_path = f'/config/auth/wireguard/{key_file}/private.key'

        if not os.path.exists(full_key_path):
            print(f'Could not find wireguard private key for migration on interface "{interface}"')
            continue

        with open(full_key_path, 'r') as f:
            key_data = f.read().strip()
            config.set(private_key_path, value=key_data)

        for peer in config.list_nodes(base + [interface, 'peer']):
            config.rename(base + [interface, 'peer', peer, 'pubkey'], 'public-key')

    try:
        with open(file_name, 'w') as f:
            f.write(config.to_string())
    except OSError as e:
        print("Failed to save the modified config: {}".format(e))
        sys.exit(1)
