#!/usr/bin/env python3
#
# Copyright (C) 2022-2024 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# T4384: pppoe: replace default-route CLI option with common CLI nodes already
#        present for DHCP

from sys import argv
from vyos.configtree import ConfigTree

if len(argv) < 2:
    print("Must specify file name!")
    exit(1)

file_name = argv[1]
with open(file_name, 'r') as f:
    config_file = f.read()

base = ['interfaces', 'pppoe']
config = ConfigTree(config_file)

if not config.exists(base):
    exit(0)

for ifname in config.list_nodes(base):
    tmp_config = base + [ifname, 'default-route']
    if config.exists(tmp_config):
        # Retrieve current config value
        value = config.return_value(tmp_config)
        # Delete old Config node
        config.delete(tmp_config)
        if value == 'none':
            config.set(base + [ifname, 'no-default-route'])

try:
    with open(file_name, 'w') as f:
        f.write(config.to_string())
except OSError as e:
    print(f'Failed to save the modified config: {e}')
    exit(1)
