#!/usr/bin/env python3
#
# Copyright (C) 2023-2024 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# T4995: pppoe, wwan, sstpc-client rename "authentication user" CLI node
#        to "authentication username"

from sys import argv

from vyos.configtree import ConfigTree

if len(argv) < 2:
    print("Must specify file name!")
    exit(1)

file_name = argv[1]
with open(file_name, 'r') as f:
    config_file = f.read()

config = ConfigTree(config_file)

for type in ['pppoe', 'sstpc-client', 'wwam']:
    base = ['interfaces', type]
    if not config.exists(base):
        continue
    for interface in config.list_nodes(base):
        auth_base = base + [interface, 'authentication', 'user']
        if config.exists(auth_base):
            config.rename(auth_base, 'username')

try:
    with open(file_name, 'w') as f:
        f.write(config.to_string())
except OSError as e:
    print(f'Failed to save the modified config: {e}')
    exit(1)
