#!/usr/bin/env python3
#
# Copyright (C) 2023-2024 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# T5034: tunnel: rename "multicast enable" CLI node to "enable-multicast"
#        valueless node.

from sys import argv
from vyos.configtree import ConfigTree

if len(argv) < 2:
    print("Must specify file name!")
    exit(1)

file_name = argv[1]
with open(file_name, 'r') as f:
    config_file = f.read()

base = ['interfaces', 'tunnel']
config = ConfigTree(config_file)

if not config.exists(base):
    exit(0)

for ifname in config.list_nodes(base):
    multicast_base = base + [ifname, 'multicast']
    if config.exists(multicast_base):
        tmp = config.return_value(multicast_base)
        print(tmp)
        # Delete old Config node
        config.delete(multicast_base)
        if tmp == 'enable':
            config.set(base + [ifname, 'enable-multicast'])

try:
    with open(file_name, 'w') as f:
        f.write(config.to_string())
except OSError as e:
    print(f'Failed to save the modified config: {e}')
    exit(1)
