#!/usr/bin/env python3
#
# Copyright (C) 2023 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from sys import argv
from vyos.configtree import ConfigTree
from vyos.validate import is_bond_member_allowed_option

if (len(argv) < 1):
    print("Must specify file name!")
    exit(1)

file_name = argv[1]
with open(file_name, 'r') as f:
    config_file = f.read()
    base = ['interfaces', 'bonding']

config = ConfigTree(config_file)

for bond in config.list_nodes(base):
    member_base = base + [bond, 'member', 'interface']
    if config.exists(member_base):
        for interface in config.return_values(member_base):
            if_base = ['interfaces', 'ethernet', interface]
            if config.exists(if_base):
                for option in config.list_nodes(if_base):
                    if not is_bond_member_allowed_option(option.replace('-','_')):
                        config.delete(if_base + [option])
try:
    with open(file_name, 'w') as f:
        f.write(config.to_string())
except OSError as e:
    print(f'Failed to save the modified config: {e}')
    exit(1)
