#!/usr/bin/env python3
#
# Copyright (C) 2023 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# T5671: change port to IANA assigned default port
# T5759: change default MTU 1450 -> 1500

from sys import argv
from sys import exit
from vyos.configtree import ConfigTree

if len(argv) < 2:
    print("Must specify file name!")
    exit(1)

file_name = argv[1]
with open(file_name, 'r') as f:
    config_file = f.read()

base = ['interfaces', 'vxlan']

config = ConfigTree(config_file)
if not config.exists(base):
    # Nothing to do
    exit(0)

for vxlan in config.list_nodes(base):
    if config.exists(base + [vxlan, 'external']):
        config.delete(base + [vxlan, 'external'])
        config.set(base + [vxlan, 'parameters', 'external'])

    if not config.exists(base + [vxlan, 'port']):
        config.set(base + [vxlan, 'port'], value='8472')

    if not config.exists(base + [vxlan, 'mtu']):
        config.set(base + [vxlan, 'mtu'], value='1450')

try:
    with open(file_name, 'w') as f:
        f.write(config.to_string())
except OSError as e:
    print(f'Failed to save the modified config: {e}')
    exit(1)
