#!/usr/bin/env python3
#
# Copyright (C) 2024 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# T6318: WiFi country-code should be set system-wide instead of per-device

from sys import argv
from sys import exit
from vyos.configtree import ConfigTree

if len(argv) < 2:
    print("Must specify file name!")
    exit(1)

file_name = argv[1]
with open(file_name, 'r') as f:
    config_file = f.read()

base = ['interfaces', 'wireless']

config = ConfigTree(config_file)
if not config.exists(base):
    # Nothing to do
    exit(0)

installed = False
for interface in config.list_nodes(base):
    cc_path = base + [interface, 'country-code']
    if config.exists(cc_path):
        tmp = config.return_value(cc_path)
        config.delete(cc_path)

        # There can be only ONE wireless country-code per device, everything
        # else makes no sense as a WIFI router can not operate in two
        # different countries
        if not installed:
            config.set(['system', 'wireless', 'country-code'], value=tmp)
            installed = True

try:
    with open(file_name, 'w') as f:
        f.write(config.to_string())
except OSError as e:
    print(f'Failed to save the modified config: {e}')
    exit(1)
