#!/usr/bin/env python3
#
# Copyright (C) 2025 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# T7388: remove "ipv6 address autoconf" from certain CLI nodes whose
#        underlaying interface does not support IPv6 neighbor discovery

from vyos.configtree import ConfigTree

base = ['interfaces']

def migrate(config: ConfigTree) -> None:
    for iftype in ['tunnel', 'wireguard', 'vti']:
        # bail out early if interface type does not exist in config
        base_iftype = base + [iftype]
        if not config.exists(base_iftype):
            continue
        for interface in config.list_nodes(base_iftype):
            base_interface = base_iftype + [interface]

            autoconf_path = base_interface + ['ipv6', 'address', 'autoconf']
            if config.exists(autoconf_path):
                # Keep behavior for IP/IPv6 gretap based tunnels which support ND/RD
                if iftype == 'tunnel' and config.return_value(
                    base_interface + ['encapsulation']) in ['gretap', 'ip6gretap']:
                    continue

                config.delete(autoconf_path)
                # delete empty CLI config under 'address' node
                if len(config.list_nodes(autoconf_path[:-1])) == 0:
                    config.delete(autoconf_path[:-1])
                # delete empty CLI config under 'ipv6' node
                if len(config.list_nodes(autoconf_path[:-2])) == 0:
                    config.delete(autoconf_path[:-2])
