#!/usr/bin/env python3
#
# Copyright (C) 2023 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# T5150: Rework CLI definitions to apply route-maps between routing daemons
#        and zebra/kernel

from sys import argv
from sys import exit

from vyos.configtree import ConfigTree

if len(argv) < 2:
    print("Must specify file name!")
    exit(1)

file_name = argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

config = ConfigTree(config_file)

ripng_base = ['protocols', 'ripng']
# Check if RIPng is configured - if so, migrate the CLI node
if config.exists(ripng_base):
    if config.exists(ripng_base + ['route-map']):
        tmp = config.return_value(ripng_base + ['route-map'])

        config.set(['system', 'ipv6', 'protocol', 'ripng', 'route-map'], value=tmp)
        config.set_tag(['system', 'ipv6', 'protocol'])
        config.delete(ripng_base + ['route-map'])

try:
    with open(file_name, 'w') as f:
        f.write(config.to_string())
except OSError as e:
    print(f'Failed to save the modified config: {e}')
    exit(1)
