#!/usr/bin/env python3
#
# Copyright (C) 2019 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
from vyos.configtree import ConfigTree

if len(sys.argv) < 2:
    print("Must specify file name!")
    sys.exit(1)

file_name = sys.argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

config = ConfigTree(config_file)
config_base = ['service', 'snmp', 'v3']

if not config.exists(config_base):
    # Nothing to do
    sys.exit(0)
else:
    # we no longer support a per trap target engine ID (https://vyos.dev/T818)
    if config.exists(config_base + ['v3', 'trap-target']):
        for target in config.list_nodes(config_base + ['v3', 'trap-target']):
            config.delete(config_base + ['v3', 'trap-target', target, 'engineid'])

    # we no longer support a per user engine ID (https://vyos.dev/T818)
    if config.exists(config_base + ['v3', 'user']):
        for user in config.list_nodes(config_base + ['v3', 'user']):
            config.delete(config_base + ['v3', 'user', user, 'engineid'])

    # we drop TSM support as there seem to be no users and this code is untested
    # https://vyos.dev/T1769
    if config.exists(config_base + ['v3', 'tsm']):
        config.delete(config_base + ['v3', 'tsm'])

    try:
        with open(file_name, 'w') as f:
            f.write(config.to_string())
    except OSError as e:
        print("Failed to save the modified config: {}".format(e))
        sys.exit(1)
