#!/bin/sh
# When power is lost right after a commit modified files, the
# system can be corrupted and e.g. login is no longer possible.
# Always sync files to the backend storage after a commit.
# https://vyos.dev/T4975
sync

