#!/usr/bin/env python3
#
# Copyright (C) 2019 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# log-modes have changed, keyword  all to any

import sys

from vyos.configtree import ConfigTree

if len(sys.argv) < 2:
    print("Must specify file name!")
    sys.exit(1)

file_name = sys.argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

ctree = ConfigTree(config_file)

if not ctree.exists(['vpn', 'ipsec', 'logging','log-modes']):
    # Nothing to do
    sys.exit(0)
else:
  lmodes = ctree.return_values(['vpn', 'ipsec', 'logging','log-modes'])
  for mode in lmodes:
    if mode == 'all':
      ctree.set(['vpn', 'ipsec', 'logging','log-modes'], value='any', replace=True)

  try:
    open(file_name,'w').write(ctree.to_string())
  except OSError as e:
    print("Failed to save the modified config: {}".format(e))
    sys.exit(1)
