#!/usr/bin/env python3

# Latest version of Debian/Systemd hostnamectl does not support a trialing dot
# in the systems hostname. Ensure that there is no trailing dot in the configured
# systems domain-name.

import sys
from vyos.configtree import ConfigTree

if (len(sys.argv) < 1):
    print("Must specify file name!")
    sys.exit(1)

file_name = sys.argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

config = ConfigTree(config_file)
if not config.exists(['system', 'domain-name']):
    # Nothing to do
    sys.exit(0)
else:
    domainname = config.return_value(['system', 'domain-name'])
    config.set(['system', 'domain-name'], value=domainname.rstrip('.'))

    try:
        with open(file_name, 'w') as f:
            f.write(config.to_string())
    except OSError as e:
        print("Failed to save the modified config: {}".format(e))
        sys.exit(1)
