#!/usr/bin/env python3
#
# Make 'system options reboot-on-panic' valueless

import sys

from vyos.configtree import ConfigTree

if len(sys.argv) < 2:
    print("Must specify file name!")
    sys.exit(1)

file_name = sys.argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

config = ConfigTree(config_file)
base = ['system', 'options']
if not config.exists(base):
    # Nothing to do
    sys.exit(0)
else:
    if config.exists(base + ['reboot-on-panic']):
        reboot = config.return_value(base + ['reboot-on-panic'])
        config.delete(base + ['reboot-on-panic'])
        # create new valueless node if action was true
        if reboot == "true":
            config.set(base + ['reboot-on-panic'])

    try:
        with open(file_name, 'w') as f:
            f.write(config.to_string())
    except OSError as e:
        print("Failed to save the modified config: {}".format(e))
        sys.exit(1)
