#!/usr/bin/env python3
#
# Copyright (C) 2022 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Migrate system syslog global archive to system logs logrotate messages

from sys import exit, argv
from vyos.configtree import ConfigTree

if len(argv) < 2:
    print("Must specify file name!")
    exit(1)

file_name = argv[1]
with open(file_name, 'r') as f:
    config_file = f.read()

base = ['system', 'syslog', 'global', 'archive']
config = ConfigTree(config_file)

if not config.exists(base):
    exit(0)

if config.exists(base + ['file']):
    tmp = config.return_value(base + ['file'])
    config.set(['system', 'logs', 'logrotate', 'messages', 'rotate'], value=tmp)

if config.exists(base + ['size']):
    tmp = config.return_value(base + ['size'])
    tmp = max(round(int(tmp) / 1024), 1) # kb -> mb
    config.set(['system', 'logs', 'logrotate', 'messages', 'max-size'], value=tmp)

config.delete(base)

try:
    with open(file_name, 'w') as f:
        f.write(config.to_string())
except OSError as e:
    print(f'Failed to save the modified config: {e}')
    exit(1)
