#!/usr/bin/env python3

# Converts "system gateway-address" option to "protocols static route 0.0.0.0/0 next-hop $gw"

import sys

from vyos.configtree import ConfigTree

if len(sys.argv) < 2:
    print("Must specify file name!")
    sys.exit(1)

file_name = sys.argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

config = ConfigTree(config_file)

if not config.exists(['system', 'gateway-address']):
    # Nothing to do
    sys.exit(0)
else:
    # Save the address
    gw = config.return_value(['system', 'gateway-address'])

    # Create the node for the new syntax
    # Note: next-hop is a tag node, gateway address is its child, not a value
    config.set(['protocols', 'static', 'route', '0.0.0.0/0', 'next-hop', gw])

    # Delete the node with the old syntax
    config.delete(['system', 'gateway-address'])

    # Now, the interesting part. Both route and next-hop are supposed to be tag nodes,
    # which you can verify with "cli-shell-api isTag $configPath".
    # They must be formatted as such to load correctly.
    config.set_tag(['protocols', 'static', 'route'])
    config.set_tag(['protocols', 'static', 'route', '0.0.0.0/0', 'next-hop'])

    try:
        with open(file_name, 'w') as f:
            f.write(config.to_string())
    except OSError as e:
        print("Failed to save the modified config: {}".format(e))
        sys.exit(1)
