#!/usr/bin/env python3

# Deletes "system package" option as it is deprecated

import sys

from vyos.configtree import ConfigTree

if len(sys.argv) < 2:
    print("Must specify file name!")
    sys.exit(1)

file_name = sys.argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

config = ConfigTree(config_file)

if not config.exists(['system', 'package']):
    # Nothing to do
    sys.exit(0)
else:
    # Delete the node with the old syntax
    config.delete(['system', 'package'])

    try:
        with open(file_name, 'w') as f:
            f.write(config.to_string())
    except OSError as e:
        print("Failed to save the modified config: {}".format(e))
        sys.exit(1)
