#!/usr/bin/env python3

# Deletes the deprecated "system package" and "service telnet" options

import sys

from vyos.configtree import ConfigTree

if (len(sys.argv) < 1):
    print("Must specify file name!")
    sys.exit(1)

file_name = sys.argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

config = ConfigTree(config_file)

if (not config.exists(['system', 'package'])) and (not config.exists(['service', 'telnet'])):
    # Nothing to do
    sys.exit(0)
else:
    # Delete the "system package" subtree
    if config.exists(['system', 'package']):
        config.delete(['system', 'package'])

    if config.exists(['service', 'telnet']):
        config.delete(['service', 'telnet'])

    try:
        with open(file_name, 'w') as f:
            f.write(config.to_string())
    except OSError as e:
        print("Failed to save the modified config: {}".format(e))
        sys.exit(1)
