#!/usr/bin/env python3
#
# Copyright (C) 2021 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# - T3344: migrate routing options from "protocols vrf" to "vrf <name> protocols"

from sys import argv
from sys import exit
from vyos.configtree import ConfigTree

if len(argv) < 2:
    print("Must specify file name!")
    exit(1)

file_name = argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

base = ['protocols', 'vrf']
config = ConfigTree(config_file)

if not config.exists(base):
    # Nothing to do
    exit(0)

vrf_base = ['vrf', 'name']
config.set(vrf_base)
config.set_tag(vrf_base)

# Copy all existing static routes to the new base node under "vrf name <name> protocols static"
for vrf in config.list_nodes(base):
    static_base = base + [vrf, 'static']
    if not config.exists(static_base):
        continue

    new_static_base = vrf_base + [vrf, 'protocols']
    config.set(new_static_base)
    config.copy(static_base, new_static_base + ['static'])
    config.set_tag(new_static_base + ['static', 'route'])

# Now delete the old configuration
config.delete(base)

try:
    with open(file_name, 'w') as f:
        f.write(config.to_string())
except OSError as e:
    print("Failed to save the modified config: {}".format(e))
    exit(1)
