#!/usr/bin/env python3
#
# Copyright (C) 2023 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from sys import argv,exit
from vyos.configtree import ConfigTree

if len(argv) < 2:
    print("Must specify file name!")
    exit(1)

file_name = argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

base = ['nat66', 'source']
new_base = ['service', 'ndp-proxy', 'interface']

config = ConfigTree(config_file)
if not config.exists(base):
    # Nothing to do
    exit(0)

for rule in config.list_nodes(base + ['rule']):
    base_rule = base + ['rule', rule]

    interface = None
    if config.exists(base_rule + ['outbound-interface', 'name']):
        interface = config.return_value(base_rule + ['outbound-interface', 'name'])
    else:
        continue

    prefix_base = base_rule + ['source', 'prefix']
    if config.exists(prefix_base):
        prefix = config.return_value(prefix_base)
        config.set(new_base + [interface, 'prefix', prefix, 'mode'], value='static')
        config.set_tag(new_base)
        config.set_tag(new_base + [interface, 'prefix'])

        if config.exists(base_rule + ['disable']):
            config.set(new_base + [interface, 'prefix', prefix, 'disable'])

try:
    with open(file_name, 'w') as f:
        f.write(config.to_string())
except OSError as e:
    print("Failed to save the modified config: {}".format(e))
    exit(1)
