#!/usr/bin/env python3
#
# Copyright (C) 2022 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from sys import argv
from sys import exit

from vyos.configtree import ConfigTree

if len(argv) < 2:
    print("Must specify file name!")
    exit(1)

file_name = argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

base = ['service', 'ids', 'ddos-protection']
config = ConfigTree(config_file)

if not config.exists(base + ['threshold']):
    # Nothing to do
    exit(0)
else:
    if config.exists(base + ['threshold', 'fps']):
        tmp = config.return_value(base + ['threshold', 'fps'])
        config.delete(base + ['threshold', 'fps'])
        config.set(base + ['threshold', 'general', 'fps'], value=tmp)
    if config.exists(base + ['threshold', 'mbps']):
        tmp = config.return_value(base + ['threshold', 'mbps'])
        config.delete(base + ['threshold', 'mbps'])
        config.set(base + ['threshold', 'general', 'mbps'], value=tmp)
    if config.exists(base + ['threshold', 'pps']):
        tmp = config.return_value(base + ['threshold', 'pps'])
        config.delete(base + ['threshold', 'pps'])
        config.set(base + ['threshold', 'general', 'pps'], value=tmp)

try:
    with open(file_name, 'w') as f:
        f.write(config.to_string())
except OSError as e:
    print(f'Failed to save the modified config: {e}')
    exit(1)
