(include_subdirs unqualified)

(executable
 (name numeric)
 (public_name numeric)
 (modules numeric)
 (libraries pcre2))

(executable
 (name url)
 (public_name url)
 (modules url)
 (libraries pcre2))

(executable
 (name file_path)
 (public_name file-path)
 (modules file_path)
 (libraries fileutils))

(executable
 (name validate_value)
 (public_name validate-value)
 (modules validate_value native_validators)
 (libraries pcre2 unix containers))

(executable
 (name list_interfaces)
 (public_name list_interfaces)
 (modules func list_interfaces)
 (libraries pcre2)
 (foreign_stubs
  (language c)
  (names iface)))

(executable
 (name vyos_op_run)
 (public_name vyos-op-run)
 (modules vyos_op_run)
 (libraries
   logs
   logs.fmt
   fmt.tty
   yojson
   mustache
   pcre2
   unix))
