#!/usr/bin/env python3

# Delete "service ssh allow-root" option

import sys

from vyos.configtree import ConfigTree

if len(sys.argv) < 2:
    print("Must specify file name!")
    sys.exit(1)

file_name = sys.argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

config = ConfigTree(config_file)

if not config.exists(['service', 'ssh', 'allow-root']):
    # Nothing to do
    sys.exit(0)
else:
    # Delete node with abandoned command
    config.delete(['service', 'ssh', 'allow-root'])

    try:
        with open(file_name, 'w') as f:
            f.write(config.to_string())
    except OSError as e:
        print("Failed to save the modified config: {}".format(e))
        sys.exit(1)
