#!/usr/bin/env python3
#
# Copyright (C) 2021 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import sys
from vyos.configtree import ConfigTree

if (len(sys.argv) < 1):
    print("Must specify file name!")
    sys.exit(1)

file_name = sys.argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

base = ['service', 'dhcp-server', 'shared-network-name']
config = ConfigTree(config_file)

if not config.exists(base):
    # Nothing to do
    exit(0)

# Run this for every instance if 'shared-network-name'
for network in config.list_nodes(base):
    base_network = base + [network]

    if not config.exists(base_network + ['subnet']):
        continue

    # Run this for every specified 'subnet'
    for subnet in config.list_nodes(base_network + ['subnet']):
        base_subnet = base_network + ['subnet', subnet]

        if config.exists(base_subnet + ['static-route']):
            prefix = config.return_value(base_subnet + ['static-route', 'destination-subnet'])
            router = config.return_value(base_subnet + ['static-route', 'router'])
            config.delete(base_subnet + ['static-route'])

            config.set(base_subnet + ['static-route', prefix, 'next-hop'], value=router)
            config.set_tag(base_subnet + ['static-route'])

try:
    with open(file_name, 'w') as f:
        f.write(config.to_string())
except OSError as e:
    print("Failed to save the modified config: {}".format(e))
    exit(1)
