#!/bin/sh
#
# Copyright (C) 2022 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ $# -lt 1 ]; then
      echo "Illegal number of parameters"
      exit 1
fi

for var in "$@"; do
    ${vyos_validators_dir}/numeric --range 1-4294967294 $var
    if [ $? -ne 0 ]; then
        exit 1
    fi
done

exit 0
