#!/bin/sh
#
# Copyright (C) 2023 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

ddclient -list-protocols | grep -vE 'cloudns|porkbun' | grep -qw $1

if [ $? -gt 0 ]; then
    echo "Error: $1 is not a valid protocol, please choose from the supported list of protocols"
    exit 1
fi

exit 0
