#!/usr/bin/env python3
#
# Copyright (C) 2020 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import re
import sys

area = sys.argv[1]

res = re.match(r'^(\d+)\.(\d+)\.(\d+)\.(\d+)$', area)
if not res:
    print("\'{0}\' is not a valid dotted decimal value".format(area))
    sys.exit(1)
else:
    components = res.groups()
    for n in range(0, 4):
        if (int(components[n]) > 255):
            print("Invalid component of a dotted decimal value: {0} exceeds 255".format(components[n]))
            sys.exit(1)

sys.exit(0)
