#!/usr/bin/env python3
#
# Copyright VyOS maintainers and contributors <maintainers@vyos.io>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import re
from sys import argv,exit

if __name__ == '__main__':
    if len(argv) != 2:
        exit(1)

    input = argv[1]
    try:
        # ethertype can be in the range 1 - 65535
        if int(input) in range(1, 65536):
            exit(0)
    except ValueError:
        pass

    pattern = "!?\\b(all|ip|ipv6|ipx|802.1Q|802_2|802_3|aarp|aoe|arp|atalk|dec|lat|localtalk|rarp|snap|x25)\\b"
    if re.match(pattern, input):
        exit(0)

    print(f'Error: {input} is not a valid ether type or protocol.')
    exit(1)
