#!/usr/bin/env python3
#
# Copyright (C) 2018 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#

import sys
import re

if len(sys.argv) == 2:
  # https://unix.stackexchange.com/questions/451368/allowed-chars-in-linux-network-interface-names
  pattern = "^([^/\s]{1,16}$)$"
  if re.match(pattern, sys.argv[1]):
    sys.exit(0)
  else:
    sys.exit(1)

