#!/usr/bin/env python3

# Validator used to check if given IPv6 prefix is of size /64 required by EUI64

from sys import argv
from sys import exit

if __name__ == '__main__':
    if len(argv) != 2:
        exit(1)

    prefix = argv[1]
    if prefix.split('/')[1] == '64':
        exit(0)

    exit(1)
