#!/usr/bin/env python3
#
# Copyright (C) 2018-2020 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import re
import sys


pattern = "^([0-9A-Fa-f]{2}[:]){5}([0-9A-Fa-f]{2})$"


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(1)
    if not re.match(pattern, sys.argv[1]):
        sys.exit(1)
    sys.exit(0)
