#!/usr/bin/python3

import sys
import re

def error(uid_range):
    print(f'Error: {uid_range} is not a valid uid or uid range')
    sys.exit(1)

if __name__ == '__main__':
    if len(sys.argv)>1:
        uid_range = sys.argv[1]
        if re.match('^[0-9]{1,5}-[0-9]{1,5}$', uid_range):
            port_1, port_2 = uid_range.split('-')
            if int(port_1) not in range(1, 248) or int(port_2) not in range(1, 248):
                error(uid_range)
            if int(port_1) > int(port_2):
                error(uid_range)
        elif uid_range.isnumeric() and int(uid_range) not in range(1, 248):
            error(uid_range)
    else:
        sys.exit(2)

    sys.exit(0)
