#!/usr/bin/env python3
#
# Copyright (C) 2024 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import re
from sys import argv,exit

if __name__ == '__main__':
    if len(argv) != 2:
        exit(1)

    input = argv[1]
    is_valid = True
    try:
        # Convert hexadecimal input to binary form
        key_bytes = bytes.fromhex(input)
    except ValueError:
        is_valid = False

    if is_valid and len(key_bytes) < 16:
        is_valid = False

    if not is_valid:
        print(f'Error: {input} is not valid psk secret.')
        exit(1)

    exit(0)