#!/usr/bin/env python3
#
# Copyright (C) 2019-2023 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import argparse
import sys

from vyos.utils.process import cmd


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--validate", action="store", required=True, help="Check if timezone is valid")
    args = parser.parse_args()

    tz_data = cmd('timedatectl list-timezones')
    tz_data = tz_data.split('\n')

    if args.validate not in tz_data:
        sys.exit("the timezone can't be found in the timezone list")
    sys.exit()
