#!/usr/bin/python3

import sys
from vyos.utils.serial import is_valid_ttyS_range

if __name__ == '__main__':
    if len(sys.argv) == 2:
        if sys.argv[1] == 'all':
            sys.exit(0)

        if not is_valid_ttyS_range(tty_range=sys.argv[1]):
            sys.exit(1)
    else:
        sys.exit(2)

    sys.exit(0)
