#!/usr/bin/env python3
#
# Copyright (C) 2020 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import re
from sys import argv, exit

if __name__ == '__main__':
    if len(argv) != 2:
        exit(1)

    vrf = argv[1]
    length = len(vrf)

    if length not in range(1, 16):
        exit(1)

    # Treat loopback interface "lo" explicitly. Adding "lo" explicitly to the
    # following regex pattern would deny any VRF name starting with lo - thuse
    # local-vrf would be illegal - and that we do not want.
    if vrf == "lo":
        exit(1)

    pattern = r'^(?!(bond|br|dum|eth|lan|eno|ens|enp|enx|gnv|ipoe|l2tp|l2tpeth|\
       vtun|ppp|pppoe|peth|tun|vti|vxlan|wg|wlan|wwan|\d)\d*(\.\d+)?(v.+)?).*$'
    if not re.match(pattern, vrf):
        exit(1)

    exit(0)
