#!/bin/sh
#
# Copyright (C) 2018-2020 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ ! -d /sys/class/ieee80211 ]; then
    echo No IEEE 802.11 physical interfaces detected
    exit 1
fi

if [ ! -e /sys/class/ieee80211/$1 ]; then
    echo Device interface "$1" does not exist
    exit 1
fi
