#!/usr/bin/env python3

# Delete "set service lldp interface <interface> location civic-based" option
# as it was broken most of the time anyways

import sys

from vyos.configtree import ConfigTree

if (len(sys.argv) < 1):
    print("Must specify file name!")
    sys.exit(1)

file_name = sys.argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

config = ConfigTree(config_file)
base = ['service', 'lldp', 'interface']
if not config.exists(base):
    # Nothing to do
    sys.exit(0)
else:
    # Delete nodes with abandoned CLI syntax
    for interface in config.list_nodes(base):
        if config.exists(base + [interface, 'location', 'civic-based']):
            config.delete(base + [interface, 'location', 'civic-based'])

    try:
        with open(file_name, 'w') as f:
            f.write(config.to_string())
    except OSError as e:
        print("Failed to save the modified config: {}".format(e))
        sys.exit(1)
