#!/usr/bin/env python3
# Copyright 2024 VyOS maintainers and contributors <maintainers@vyos.io>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library.  If not, see <http://www.gnu.org/licenses/>.
# Renames ncp-ciphers option to data-ciphers

from vyos.configtree import ConfigTree

def migrate(config: ConfigTree) -> None:
    ovpn_intfs = config.list_nodes(['interfaces', 'openvpn'], path_must_exist=False)
    for i in ovpn_intfs:
        #Rename 'encryption ncp-ciphers' with 'encryption data-ciphers'
        ncp_cipher_path = ['interfaces', 'openvpn', i, 'encryption', 'ncp-ciphers']
        if config.exists(ncp_cipher_path):
            config.rename(ncp_cipher_path, 'data-ciphers')
