#!/usr/bin/env python3

# Add commit-revisions option if it doesn't exist

import sys

from vyos.configtree import ConfigTree

if len(sys.argv) < 2:
    print("Must specify file name!")
    sys.exit(1)

file_name = sys.argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

config = ConfigTree(config_file)

if config.exists(['system', 'config-management', 'commit-revisions']):
    # Nothing to do
    sys.exit(0)
else:
    config.set(['system', 'config-management', 'commit-revisions'], value='200')

    try:
        with open(file_name, 'w') as f:
            f.write(config.to_string())
    except OSError as e:
        print("Failed to save the modified config: {}".format(e))
        sys.exit(1)
