#!/usr/bin/env python3
#
# Copyright (C) 2023 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# T5834: Rename 'enable-default-log' to 'default-log'
# From
    # set firewall ... filter enable-default-log
    # set firewall ... name <name> enable-default-log
# To
    # set firewall ... filter default-log
    # set firewall ... name <name> default-log

from sys import argv
from sys import exit

from vyos.configtree import ConfigTree

if len(argv) < 2:
    print("Must specify file name!")
    exit(1)

file_name = argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

base = ['firewall']
config = ConfigTree(config_file)

if not config.exists(base):
    # Nothing to do
    exit(0)

for family in ['ipv4', 'ipv6', 'bridge']:
    if config.exists(base + [family]):
        for hook in ['forward', 'input', 'output', 'name']:
            if config.exists(base + [family, hook]):
                for priority in config.list_nodes(base + [family, hook]):
                    if config.exists(base + [family, hook, priority, 'enable-default-log']):
                        config.rename(base + [family, hook, priority, 'enable-default-log'], 'default-log')

try:
    with open(file_name, 'w') as f:
        f.write(config.to_string())
except OSError as e:
    print("Failed to save the modified config: {}".format(e))
    exit(1)
