#!/usr/bin/env python3
#
# Copyright (C) 2022-2024 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# T6394: Migrate conntrack timeout options to firewall global-options
    # from: set system conntrack timeout ..
    # to: set firewall global-options timeout ...

from vyos.configtree import ConfigTree

firewall_base = ['firewall', 'global-options']
conntrack_base = ['system', 'conntrack', 'timeout']

def migrate(config: ConfigTree) -> None:
    if not config.exists(conntrack_base):
        # Nothing to do
        return

    for protocol in ['icmp', 'tcp', 'udp', 'other']:
        if config.exists(conntrack_base + [protocol]):
            if not config.exists(firewall_base + ['timeout']):
                config.set(firewall_base + ['timeout'])

            config.copy(conntrack_base + [protocol], firewall_base + ['timeout', protocol])
            config.delete(conntrack_base + [protocol])
