#!/usr/bin/env python3

# Delete depricated outside-nexthop address

import sys

from vyos.configtree import ConfigTree

if len(sys.argv) < 2:
    print("Must specify file name!")
    sys.exit(1)

file_name = sys.argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

config = ConfigTree(config_file)

cfg_base = ['vpn', 'l2tp', 'remote-access']
if not config.exists(cfg_base):
    # Nothing to do
    sys.exit(0)
else:
    if config.exists(cfg_base + ['outside-nexthop']):
        config.delete(cfg_base + ['outside-nexthop'])

    try:
        with open(file_name, 'w') as f:
            f.write(config.to_string())
    except OSError as e:
        print("Failed to save the modified config: {}".format(e))
        sys.exit(1)
