#!/bin/bash

while [ ! -f /tmp/vyos-config-status ]
do
  sleep 1
done

status=$(cat /tmp/vyos-config-status)

if [ -z "$1" ]; then
  if [ $status -ne 0 ]; then
    echo "Configuration error"
  else
    echo "Configuration success"
  fi
fi
