<!-- include start from serial/service/direct.xml.i -->
<node name="direct">
  <properties>
    <help>Direct connection profile</help>
  </properties>
  <children>
    <leafNode name="main-hostport">
      <properties>
        <help>Connect to main host port</help>
        <valueHelp>
          <format>u32:1-65535</format>
          <description>Port number</description>
        </valueHelp>
        <constraint>
          <validator name="numeric" argument="--range 1-65535"/>
        </constraint>
      </properties>
    </leafNode>
    <leafNode name="main-hostname">
      <properties>
        <help>Connect to main host</help>
        <valueHelp>
          <format>ipv4</format>
          <description>IP address of main host</description>
        </valueHelp>
        <valueHelp>
          <format>ipv6</format>
          <description>IPv6 address of main host</description>
        </valueHelp>
        <valueHelp>
          <format>hostname</format>
          <description>Fully qualified host name of main host</description>
        </valueHelp>
        <constraint>
          <validator name="ip-address"/>
          <validator name="fqdn"/>
        </constraint>
      </properties>
    </leafNode>
    <node name="tcp">
      <properties>
        <help>tcp settings</help>
      </properties>
      <children>
        <node name="multihost">
          <properties>
            <help>Connect to multiple hosts [tcp only]</help>
          </properties>
          <children>
            #include <include/serial/service/utils/multihost.xml.i>
          </children>
        </node>
      </children>
    </node>
    <node name="telnet">
      <properties>
        <help>telnet settings</help>
      </properties>
      <children>
        #include <include/serial/service/utils/term-type.xml.i>
        <leafNode name="map-cr-to-crlf">
          <properties>
            <help>Enable mapping carriage returns (CR) to carriage return line feed (CRLF)</help>
            <valueless/>
          </properties>
        </leafNode>
      </children>
    </node>
    <node name="ssh">
      <properties>
        <help>ssh settings</help>
      </properties>
      <children>
        #include <include/serial/service/utils/term-type.xml.i>
        <leafNode name="compression">
          <properties>
            <help>Enable requesting compression of all data</help>
            <valueless/>
          </properties>
        </leafNode>
        <node name="authentication">
          <properties>
            <help>authentication</help>
          </properties>
          <children>
            <leafNode name="keyboard">
              <properties>
                <help>Keyboard authentication</help>
                <valueless/>
              </properties>
            </leafNode>
            <leafNode name="public-key">
              <properties>
                <help>Public key authentication</help>
                <completionHelp>
                  <list>rsa dsa</list>
                </completionHelp>
                <constraint>
                  <regex>(rsa|dsa)</regex>
                </constraint>
              </properties>
              <defaultValue>dsa</defaultValue>
            </leafNode>
          </children>
        </node>
        <leafNode name="login-name">
          <properties>
            <help>Specifies the user to log in as on the remote machine</help>
            <constraint>
              <regex>.{0,63}</regex>
            </constraint>
            <constraintErrorMessage>Login username string too long (limit 63 characters)</constraintErrorMessage>
          </properties>
        </leafNode>
        <leafNode name="strict-host-key">
          <properties>
            <help>Enable controlling logins to machines whose host key is not known or has changed</help>
            <valueless/>
          </properties>
        </leafNode>
        <leafNode name="verbose">
          <properties>
            <help>Enable displaying debug messages on the terminal</help>
            <valueless/>
          </properties>
        </leafNode>
        <leafNode name="ciphers">
          <properties>
            <help>Allowed ciphers</help>
            <completionHelp>
              <!-- generated by ssh -Q cipher | tr '\n' ' ' as this will not change dynamically  -->
              <list>3des-cbc aes128-cbc aes192-cbc aes256-cbc aes128-ctr aes192-ctr aes256-ctr aes128-gcm@openssh.com aes256-gcm@openssh.com chacha20-poly1305@openssh.com</list>
            </completionHelp>
              <constraint>
                <regex>(3des-cbc|aes128-cbc|aes192-cbc|aes256-cbc|aes128-ctr|aes192-ctr|aes256-ctr|aes128-gcm@openssh.com|aes256-gcm@openssh.com|chacha20-poly1305@openssh.com)</regex>
              </constraint>
            <multi/>
          </properties>
        </leafNode>
      </children>
    </node>
    <leafNode name="initiate-any-char">
      <properties>
        <help>Connect when any data is received [main only]</help>
        <valueless/>
      </properties>
    </leafNode>
    <leafNode name="initiate-specific-char">
      <properties>
        <help>Connect when specific character received [main only]</help>
        <valueHelp>
          <format>txt</format>
          <description>ASCII char in hex value</description>
        </valueHelp>
        <constraint>
          <validator name="hex"/>
        </constraint>
      </properties>
    </leafNode>
  </children>
</node>
<!-- include end -->
