#!/usr/bin/env python3
#
# Copyright (C) 2022 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Delete depricated outside-nexthop address

import sys

from vyos.configtree import ConfigTree

if len(sys.argv) < 2:
    print("Must specify file name!")
    sys.exit(1)

file_name = sys.argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

config = ConfigTree(config_file)

cfg_base = ['vpn', 'openconnect']

if not config.exists(cfg_base):
    # Nothing to do
    sys.exit(0)
else:
    if config.exists(cfg_base + ['authentication', 'mode']):
        if config.return_value(cfg_base + ['authentication', 'mode']) == 'radius':
            # if "mode value radius", change to "mode + valueless node radius"
            config.delete_value(cfg_base + ['authentication','mode'], 'radius')
            config.set(cfg_base + ['authentication', 'mode', 'radius'], value=None)
        elif config.return_value(cfg_base + ['authentication', 'mode']) == 'local':
            # if "mode local", change to "mode + node local value password"
            config.delete_value(cfg_base + ['authentication', 'mode'], 'local')
            config.set(cfg_base + ['authentication', 'mode', 'local'], value='password')
    try:
        with open(file_name, 'w') as f:
            f.write(config.to_string())
    except OSError as e:
        print("Failed to save the modified config: {}".format(e))
        sys.exit(1)
