#!/usr/bin/env python3

# Conntrack syntax version 3
# Enables all conntrack modules (previous default behaviour) and omits manually disabled modules.

import os
import sys

from vyos.configtree import ConfigTree
from vyos.version import get_version

if len(sys.argv) < 1:
    print('Must specify file name!')
    sys.exit(1)

filename = sys.argv[1]

with open(filename, 'r') as f:
    config = ConfigTree(f.read())

# Get all conntrack modules supported through the CLI.
module_templates_dir = '/opt/vyatta/share/vyatta-cfg/templates/system/conntrack/modules'
module_path = ['system', 'conntrack', 'modules']

for module in [f.name for f in os.scandir(module_templates_dir) if f.is_dir()]:
    # 'disable' is being phased out.
    if config.exists(module_path + [module, 'disable']):
        config.delete(module_path + [module])
    # If it wasn't manually 'disable'd, it was enabled by default.
    # So we 'enable' it in the new syntax.
    else:
        config.set(module_path + [module, 'enable'])

try:
    if config.exists(module_path):
        with open(filename, 'w') as f:
            f.write(config.to_string())
except OSError as e:
    print(f'Failed to save the modified config: {e}')
    sys.exit(1)
