#!/usr/bin/env python3
#
# Copyright (C) 2020 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# - Rename SSTP ppp-settings node to ppp-options to make use of a common
#   Jinja Template to render Accel-PPP services

from vyos.configtree import ConfigTree
from sys import argv
from sys import exit

if (len(argv) < 1):
    print("Must specify file name!")
    exit(1)

file_name = argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

config = ConfigTree(config_file)
base_path = ['vpn', 'sstp']
if not config.exists(base_path):
    # Nothing to do
    exit(0)
else:
    if config.exists(base_path + ['ppp-settings']):
        config.rename(base_path + ['ppp-settings'], 'ppp-options')

    config_ns = base_path + ['network-settings', 'name-server']
    if config.exists(config_ns):
        config.copy(config_ns, base_path + ['name-server'])
        config.delete(config_ns)

    config_mtu = base_path + ['network-settings', 'mtu']
    if config.exists(config_mtu):
        config.copy(config_mtu, base_path + ['mtu'])
        config.delete(config_mtu)

    try:
        with open(file_name, 'w') as f:
            f.write(config.to_string())
    except OSError as e:
        print("Failed to save the modified config: {}".format(e))
        exit(1)
