name: "Open PRs Conflicts checker"
on:
  push:
    branches:
      - rolling
      - sagitta
      - circinus
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  check-pr-conflict-call:
    uses: vyos/.github/.github/workflows/check-pr-conflict.yml@production
    secrets: inherit
