
name: "PR Conflicts checker"
on:
  pull_request_target:
    branches:
      - current
    types: [synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  check-pr-conflict-call:
    uses: vyos/.github/.github/workflows/check-pr-merge-conflict.yml@current
    secrets: inherit
