name: "Open PRs Conflicts checker"
on:
  push:
    branches:
      - current
      - sagitta
      - circinus

permissions:
  actions: write
  contents: read

jobs:
  check-pr-conflict-call:
    uses: vyos/.github/.github/workflows/check-open-prs-conflict.yml@T7445-open-prs-conflict-check
    secrets: inherit
