
name: "PR Conflicts checker"
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull Request Number"
        required: true
        type: string

permissions:
  pull-requests: write
  contents: read

jobs:
  check-pr-conflict-call:
    uses: vyos/.github/.github/workflows/check-pr-merge-conflict.yml@T7445-open-prs-conflict-check
    secrets: inherit
    with:
      pr_number: ${{ inputs.pr_number }}
