name: Lint py code with ruff
on:
  pull_request_target:
    branches:
      - current

permissions:
  pull-requests: write
  contents: read

jobs:
  ruff-lint:
    uses: vyos/.github/.github/workflows/lint-with-ruff.yml@current
    secrets: inherit
