name: Auto-Close Pull Requests Circinus

on:
  pull_request_target:
    types:
      - opened
    branches:
      - circinus

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        # Optional. Post a issue comment just before closing a pull request.
        comment: "Pull requests to this branch are not accepted and have been closed automatically."
        github_token: ${{ secrets.PAT }}
