name: Auto-Close Pull Requests

on:
  pull_request_target:
    types:
      - opened
      - reopened
    branches:
      - circinus
      - sagitta

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'vyos'
    steps:
    - uses: superbrothers/close-pull-request@9c18513d320d7b2c7185fb93396d0c664d5d8448 #v3
      with:
        comment: "Pull requests to this branch are not accepted and have been closed automatically."
        github_token: ${{ github.token }}
