name: Update submodule vyos-1x
on:
  workflow_dispatch:
  schedule:
  # 06:00 UTC on Monday
    - cron:  '0 6 * * 1'
jobs:
  update_rolling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}

      - name: update submodule
        run: |
          git submodule status
          git submodule update --init --force
          cd docs/_include/vyos-1x
          git checkout sagitta
          git pull
          git submodule status
      - name: update releasenotes
        env:
          PHABRICATOR_API: ${{ secrets.PHABRICATOR_API }}
        if: env.PHABRICATOR_API != null
        run: |
          pip3 install phabricator==0.8.0
          python3 docs/_ext/releasenotes.py -t ${{ secrets.PHABRICATOR_API }} -b circinus sagitta equuleus
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PR_ACTION_DOCUMENTATION_SUBMODULE_UPDATE }}
          commit-message: "GitHub: update rolling branch"
          title: "GitHub: update rolling branch"
          body: |
            Autoupdate vyos-1x submodule
            update releasenotes
          branch: update-dependencies-rolling
          delete-branch: true

  update_sagitta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}
          ref: sagitta
      - name: update submodule
        run: |
          git submodule status
          git submodule update --init --force
          cd docs/_include/vyos-1x
          git checkout sagitta
          git pull
          git submodule status
      - name: update releasenotes
        env:
          PHABRICATOR_API: ${{ secrets.PHABRICATOR_API }}
        if: env.PHABRICATOR_API != null
        run: |
          pip3 install phabricator==0.8.0
          python3 docs/_ext/releasenotes.py -t ${{ secrets.PHABRICATOR_API }} -b sagitta equuleus
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PR_ACTION_DOCUMENTATION_SUBMODULE_UPDATE }}
          commit-message: "GitHub: update sagitta branch"
          title: "GitHub: update sagitta branch"
          body: |
            Autoupdate vyos-1x submodule
            update releasenotes
          branch: update-dependencies-sagitta
          delete-branch: true


  update_equuleus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}
          ref: equuleus
      - name: update submodule
        run: |
          git submodule status
          git submodule update --init --force
          cd docs/_include/vyos-1x
          git checkout equuleus
          git pull
          git submodule status
      - name: update releasenotes
        env:
          PHABRICATOR_API: ${{ secrets.PHABRICATOR_API }}
        if: env.PHABRICATOR_API != null
        run: |
          pip3 install phabricator==0.8.0
          python3 docs/_ext/releasenotes.py -t ${{ secrets.PHABRICATOR_API }} -b equuleus
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PR_ACTION_DOCUMENTATION_SUBMODULE_UPDATE }}
          commit-message: "GitHub: update equuleus branch"
          title: "GitHub: update equuleus branch"
          body: |
            Autoupdate vyos-1x submodule
            update releasenotes
          branch: update-dependencies-equuleus
          delete-branch: true
