name: Trigger VyOS ISO integration Test

on:
  pull_request_target:
    branches:
      - current
      - circinus
      - sagitta

permissions:
  pull-requests: write
  contents: read

jobs:
  package-smoketest:
    uses: vyos/.github/.github/workflows/package-smoketest.yml@current
    secrets: inherit
