#!/usr/bin/env python3

# Convert "service pppoe-server authentication radius-server  node key"
# to:
# "service pppoe-server authentication radius-server node secret"  

import sys

from vyos.config.tree import ConfigTree

if (len(sys.argv) < 1):
    print("Must specify file name!")
    sys.exit(1)

file_name = sys.argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

ctree = ConfigTree(config_file)


if not ctree.exists(['service', 'pppoe-server', 'authentication','radius-server']):
    # Nothing to do
    sys.exit(0)
else:
  nodes = ctree.list_nodes(['service', 'pppoe-server', 'authentication','radius-server'])
  for node in nodes:
    if ctree.exists(['service', 'pppoe-server', 'authentication', 'radius-server', node, 'key']):
      val = ctree.return_value(['service', 'pppoe-server', 'authentication', 'radius-server', node, 'key'])
      ctree.set(['service', 'pppoe-server', 'authentication', 'radius-server', node, 'secret'], value=val, replace=False)
      ctree.delete(['service', 'pppoe-server', 'authentication', 'radius-server', node, 'key'])
  try:
    open(file_name,'w').write(ctree.to_string())
  except OSError as e:
    print("Failed to save the modified config: {}".format(e))
    sys.exit(1)
