#!/usr/bin/env python3
#
# Copyright (C) 2020-2024 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# change mppe node to a leaf node with value prefer

from sys import argv, exit
from vyos.configtree import ConfigTree

if len(argv) < 2:
    print("Must specify file name!")
    exit(1)

file_name = argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

config = ConfigTree(config_file)
base = ['service', 'pppoe-server']
if not config.exists(base):
    # Nothing to do
    exit(0)
else:
    mppe_base = base + ['ppp-options', 'mppe']
    if config.exists(mppe_base):
        # get current values
        tmp = config.list_nodes(mppe_base)
        # drop node(s) first ...
        config.delete(mppe_base)

        print(tmp)
        # set new value based on preference
        if 'require' in tmp:
            config.set(mppe_base, value='require')
        elif 'prefer' in tmp:
            config.set(mppe_base, value='prefer')
        elif 'deny' in tmp:
            config.set(mppe_base, value='deny')

    try:
        with open(file_name, 'w') as f:
            f.write(config.to_string())
    except OSError as e:
        print("Failed to save the modified config: {}".format(e))
        exit(1)
