#!/usr/bin/env python3
#
# Copyright (C) 2020 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Convert "service pppoe-server interface ethX" to: "service pppoe-server interface ethX {}"

from sys import argv, exit
from vyos.configtree import ConfigTree

if len(argv) < 2:
    print("Must specify file name!")
    exit(1)

file_name = argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

ctree = ConfigTree(config_file)
cbase = ['service', 'pppoe-server','interface']

if not ctree.exists(cbase):
    exit(0)
else:
    nics = ctree.return_values(cbase)
    # convert leafNode to a tagNode
    ctree.set(cbase)
    ctree.set_tag(cbase)
    for nic in nics:
        ctree.set(cbase + [nic])

    try:
        open(file_name,'w').write(ctree.to_string())
    except OSError as e:
        print("Failed to save the modified config: {}".format(e))
        exit(1)
