#!/usr/bin/env python3
#
# Copyright (C) 2022 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# - T4703: merge vlan-id and vlan-range to vlan CLI node

from vyos.configtree import ConfigTree
from sys import argv
from sys import exit

if len(argv) < 2:
    print("Must specify file name!")
    exit(1)

file_name = argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

config = ConfigTree(config_file)
base_path = ['service', 'pppoe-server', 'interface']
if not config.exists(base_path):
    # Nothing to do
    exit(0)

for interface in config.list_nodes(base_path):
    for vlan in ['vlan-id', 'vlan-range']:
        if config.exists(base_path + [interface, vlan]):
            print(interface, vlan)
            for tmp in config.return_values(base_path + [interface, vlan]):
                config.set(base_path + [interface, 'vlan'], value=tmp, replace=False)
            config.delete(base_path + [interface, vlan])

try:
    with open(file_name, 'w') as f:
        f.write(config.to_string())
except OSError as e:
    print(f'Failed to save the modified config: {e}')
    exit(1)

