#!/usr/bin/env python3
#
# Copyright (C) 2024 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Migration of pado-delay options

from sys import argv
from sys import exit
from vyos.configtree import ConfigTree

if len(argv) < 2:
    print("Must specify file name!")
    exit(1)

file_name = argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

config = ConfigTree(config_file)
base = ['service', 'pppoe-server', 'pado-delay']
if not config.exists(base):
    exit(0)

pado_delay = {}
for delay in config.list_nodes(base):
    sessions = config.return_value(base + [delay, 'sessions'])
    pado_delay[delay] = sessions

# need to define delay for latest sessions
sorted_delays = dict(sorted(pado_delay.items(), key=lambda k_v: int(k_v[1])))
last_delay = list(sorted_delays)[-1]

# Rename last delay -> disable
tmp = base + [last_delay]
if config.exists(tmp):
    config.rename(tmp, 'disable')

try:
    with open(file_name, 'w') as f:
        f.write(config.to_string())
except OSError as e:
    print("Failed to save the modified config: {}".format(e))
    exit(1)
